export const GET_NESTED_ASSETS = "GET_NESTED_ASSET";
export const GET_FLAT_LIST_ASSETS = "GET_FLAT_LIST_ASSETS";
export const GET_CONFIGURED_RECOMMENDATION_LIST = "GET_CONFIGURED_RECOMMENDATION_LIST";

