language: csharp
mono: none 
solution: ../RecommendationEngine/RecommendationEngine.sln
dotnet: 3.1

script:
  - cd RecommendationEngine
  - dotnet restore RecommendationEngine.sln
  - dotnet build RecommendationEngine.sln
  - dotnet test --collect:"XPlat Code Coverage"
  - bash <(curl -s https://codecov.io/bash) -cF backend
  - cd RecommendationEngine
  - cd FrontEnd
  - npm run test
  - bash <(curl -s https://codecov.io/bash) -cF frontend
