language: csharp
mono: none 
solution: ../RecommendationEngine/RecommendationEngine.sln
dotnet: 3.1

script:
  - cd RecommendationEngine
  - dotnet restore RecommendationEngine.sln
  - dotnet build RecommendationEngine.sln
  - dotnet test
  - cd RecommendationEngine
  - cd FrontEnd
  - npm run test