language: csharp
mono: none 
solution: ../RecommendationEngine/RecommendationEngine.sln
dotnet: 3.1

script:
  - cd RecommendationEngine
  - dotnet restore RecommendationEngine.sln
  - dotnet build RecommendationEngine.sln
  - dotnet test --collect:"XPlat Code Coverage"
  - cd RecommendationEngine
  - cd FrontEnd
  - npm install codecov -g
  - npm run test
after_success:
  - codecov
