language: csharp
mono: none 
solution: ../RecommendationEngine/RecommendationEngine.sln
dotnet: 3.1

cache:
  npm: true
  # cache both npm modules and Cypress binary
  directories:
    - ~/.cache

script:
  - cd RecommendationEngine
  - dotnet restore RecommendationEngine.sln
  - dotnet build RecommendationEngine.sln
  - dotnet test --collect:"XPlat Code Coverage"
  - bash <(curl -s https://codecov.io/bash) -cF backend
  - cd RecommendationEngine
  - cd FrontEnd
  # - npm run test
  - npm run test:ci
  - bash <(curl -s https://codecov.io/bash) -cF frontend
