matrix:
  include:
    - language: cshap
      mono: none
      solution: ../RecommendationEngine/RecommendationEngine.sln
      dotnet: 3.1
      before_script:
        - cd RecommendationEngine
      script:
        - dotnet restore RecommendationEngine.sln
        - dotnet build RecommendationEngine.sln
        - dotnet test --collect:"XPlat Code Coverage"
        - bash <(curl -s https://codecov.io/bash) -cF backend

    - language: node_js
      nodejs: 
        - 13
      before_script:
        - cd RecommendationEngine
        - cd RecommendationEngine
        - cd FrontEnd
      script:
        - npm ci
        - npm run test
        - npm run test:ci
        - bash <(curl -s https://codecov.io/bash) -cF frontend
