language: csharp
mono: none 
solution: ../RecommendationEngine/RecommendationEngine.sln
dotnet: 3.1

# install:
#   - dotnet restore .RecommendationEngine/RecommendationEngine.sln

script:
  - cd RecommendationEngine
  - dotnet restore RecommendationEngine.sln


# script:
# #  - msbuild /p:Configuration=Release solution-name.sln
#  - dotnet build ./RecommendationEngine.sln
#  - dotnet test 

# before_deploy:
#  - dotnet pack -c Release

# # deploy:
# #   skip_cleanup: true
# #   provider: script
# #   script: dotnet nuget push ./RecommendationEngine/bin/Release/RecommendationEngine.*.nupkg  -k $NUGET_API -s https://api.nuget.org/v3/index.json --skip-duplicate
# #   on:
# #     branch: master
# #     branch: develop