coverage:
  round: up
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        threshold: 10%
ignore:
  - "RecommendationEngine/Models"  # ignore models
  - "RecommendationEngine/RecommendationEngine/Repositories" #ignore repositories
  - "RecommendationEngine/RecommendationEngine/Services/ExternalAPI"
  - "RecommendationEngine/RecommendationSchedulerTests"
  - "RecommendationEngine/RecommendationEngine/Startup.cs"