version: '3.3'
services:
  client:
    build: './RecommendationEngine'
    environment:
      DriveAPIKey: ''
      DBServer: 'db'
      DBPort: '3306'
    ports:
      - '5000:80'
    depends_on:
       - db
  db:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: 'RecommendationEngine'
      # Password for root access
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '50024:3306'
      # Where our data will be persisted
    volumes:
      - recommendation-engine:/var/lib/mysql
    
# Names our volume
volumes:
  recommendation-engine: