//These are constants used in the dispatched actions.
export const UPDATE_RECOMMENDATION_TEMPLATE_NAME = "UPDATE_RECOMMENDATION_TEMPLATE_NAME";
export const UPDATE_RECOMMENDATION_TEMPLATE_DESCRIPTION = "UPDATE_RECOMMENDATION_TEMPLATE_DESCRIPTION";
export const UPDATE_RECOMMENDATION_TEMPLATE_INPUTLIST = "UPDATE_RECOMMENDATION_TEMPLATE_INPUTLIST";
export const UPDATE_RECOMMENDATION_TEMPLATE_ALGORITHM = "UPDATE_RECOMMENDATION_TEMPLATE_ALGORITHM";
export const UPDATE_TITLE = "UPDATE_TITLE";
export const UPDATE_ASSET = "UPDATE_ASSET";
export const UPDATE_PREFERRED_SCENARIO = "UPDATE_PREFERRED_SCENARIO";
export const UPDATE_GRANULARITY = "UPDATE_GRANULARITY";
export const UPDATE_REPEAT_DAY = "UPDATE_REPEAT_DAY";
export const UPDATE_REPEAT_DATE = "UPDATE_REPEAT_DATE";
export const UPDATE_REPEAT_TIME = "UPDATE_REPEAT_TIME";
export const TOGGLE_DIALOG = "TOGGLE_DIALOG";
export const CLEAR = "CLEAR";