//These are constants used in the dispatched actions.
export const UPDATE_RECOMMENDATION_TEMPLATE = "UPDATE_RECOMMENDATION_TEMPLATE";
export const UPDATE_TITLE = "UPDATE_TITLE";
export const UPDATE_ASSET = "UPDATE_ASSET";
export const UPDATE_PREFERRED_SCENARIO = "UPDATE_PREFERRED_SCENARIO";
export const UPDATE_GRANULARITY = "UPDATE_GRANULARITY";
export const UPDATE_REPEAT_DAY = "UPDATE_REPEAT_DAY";
export const UPDATE_REPEAT_DATE = "UPDATE_REPEAT_DATE";
export const UPDATE_REPEAT_TIME = "UPDATE_REPEAT_TIME";
export const UPDATE_CENTERPOINT_INCREMENT = 'UPDATE_CENTERPOINT_INCREMENT';
export const UPDATE_SPAN_INCREMENT = 'UPDATE_SPAN_INCREMENT';
export const UPDATE_ACCELERATOR = 'UPDATE_ACCELERATOR';
export const UPDATE_SOILING_SEASON_BUFFER = 'UPDATE_SOILING_SEASON_BUFFER';
export const TOGGLE_DIALOG = "TOGGLE_DIALOG";
export const CLEAR = "CLEAR";