//These are constants used in the dispatched actions.
export const OPEN_SCHEDULE_DRILLDOWN = "OPEN_SCHEDULE_DRILLDOWN";
export const OPEN_RESULT_DRILLDOWN = "OPEN_RESULTS_DRILLDOWN";
export const OPEN_ASSET_TREEVIEW = "OPEN_ASSET_TREEVIEW";
export const CLOSE_SCHEDULE_DRILLDOWN = "CLOSE_SCHEDULE_DRILLDOWN";
export const CLOSE_RESULT_DRILLDOWN = "CLOSE_RESULT_DRILLDOWN";
export const CLOSE_ASSET_TREEVIEW = "CLOSE_ASSET_TREEVIEW";
export const CHANGE_TAB_INDEX = "CHANGE_TAB_INDEX";
export const CLOSE_ALL = "CLOSE_ALL";
export const UPDATE_SCHEDULE_DRILLDOWN = "UPDATE_SCHEDULE_DRILLDOWN";