# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
      - image: circleci/node:13.8
    environment:
      CODECOV_TOKEN: "2d7c7c81-fc23-4479-b769-85dd6b186196"
    steps:
      - checkout
      - run:
          name: Restore Backend
          command: dotnet restore RecommendationEngine.sln
          working_directory: ~/RecommendationEngine
      - run:
          name: Build Backend
          command: dotnet build RecommendationEngine.sln
          working_directory: ~/RecommendationEngine
      - run:
          name: Running Backend Tests
          command: dotnet test --collect:"XPlat Code Coverage"
          working_directory: ~/RecommendationEngine
      - run:
          name: Running Backend Tests
          command: bash <(curl -s https://codecov.io/bash) -cF backend
          working_directory: ~/RecommendationEngine
      - run:
          name: Running Backend Tests
          command: dotnet test --collect:"XPlat Code Coverage"
          working_directory: ~/RecommendationEngine
      - run:
          name: Uploading Backend Tests Coverage
          command: bash <(curl -s https://codecov.io/bash) -cF backend
          working_directory: ~/RecommendationEngine/RecommendationEngine/FrontEnd
      - run:
          name: Installing Frontend Dependencies
          command: npm ci
          working_directory: ~/RecommendationEngine/RecommendationEngine/FrontEnd
      - run:
          name: Running Frontend Tests
          command: npm run test:ci
          working_directory: ~/RecommendationEngine/RecommendationEngine/FrontEnd
      - run:
          name: Uploading Frontend Tests Coverage
          command: bash <(curl -s https://codecov.io/bash) -cF frontend
          working_directory: ~/RecommendationEngine/RecommendationEngine/FrontEnd