// describe('Manage Recommendation drawer Dialog', () => {

//     beforeEach(() => {
//         cy.visit('/recommendations-manage');
//     })
//     it("Checks if the manage recommendation table opens", () => {
//         cy.get(':nth-child(1) > .primaryKey').click()
//         cy.wait(500)
//     })

//     it("Finds all elements in the manage Recommendation Table", () => {
//         cy.get(':nth-child(1) > .primaryKey').click()
//         cy.wait(500)
//         cy.get('#react-tabs-0').should('exist')
//         cy.wait(500)
//         cy.get('#react-tabs-0 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').should('exist')
//         cy.wait(500)
//         cy.get('.drawer-title').should('exist')
//         cy.wait(500)
//         cy.get('.drawer-subtitle').should('exist')
//         cy.wait(500)
//         cy.get('.recommendationType > .value-title').should('exist')
//         cy.wait(500)
//         cy.get(':nth-child(3) > .assets').should('exist')
//         cy.wait(500)
//         cy.get('.inputs').should('exist')
//         cy.wait(500)
//         cy.get('.MuiGrid-grid-xs-4').should('exist')
//         cy.wait(500)
//         cy.get(':nth-child(6) > .assets > .value-title').should('exist')
//         cy.wait(500)
//         cy.get(':nth-child(6) > .assets > .values').should('exist')
//         cy.wait(500)
//         cy.get(':nth-child(7) > .assets > .value-title').should('exist')
//         cy.wait(500)
//         cy.get(':nth-child(7) > .assets > .value-title').should('exist')
//         cy.wait(500)
//         cy.get(':nth-child(8) > .value-title').should('exist')
//         cy.wait(500)
//         cy.get('.last-five-status > :nth-child(1)').should('exist')
//         cy.wait(500)
//         cy.get('.last-five-status > :nth-child(2)').should('exist')
//         cy.wait(500)
//         cy.get('.last-five-status > :nth-child(3)').should('exist')
//         cy.wait(500)
//         cy.get('.last-five-status > :nth-child(4)').should('exist')
//         cy.wait(500)
//         cy.get('.last-five-status > :nth-child(5)').should('exist')
//         cy.wait(500)
//         cy.get(':nth-child(9) > .value-title').should('exist')
//         cy.wait(500)
//         cy.get('.last-five-status > :nth-child(2)').should('exist')
//         cy.wait(500)
//         cy.get(':nth-child(9) > .value-title').click()
//     })

//     it("Checks if the manage recommendation table closes", () => {
//         cy.get(':nth-child(1) > .primaryKey').click()
//         cy.wait(500)
//         cy.get('#react-tabs-0 > .MuiButtonBase-root > .MuiIconButton-label > .MuiSvgIcon-root').click()
//         cy.wait(500)
//     })

//     it("Clicks on delete button", ()=>{
//         cy.get(':nth-child(2) > .primaryKey').click()
//         cy.wait(500)
//         cy.get('.delete-button').click()
//         cy.wait(500)
//         cy.get('#deleteButton').click()
//         cy.wait(500)
//     })

//     it("Clicks on cancel button", ()=>{
//         cy.get(':nth-child(1) > .primaryKey').click()
//         cy.wait(500)
//         cy.get('.delete-button').click()
//         cy.wait(500)
//         cy.get('#cancelButton').click()
//         cy.wait(500)
//     })

//     it("closes delete recommendation pop up", ()=>{
//         cy.get(':nth-child(1) > .primaryKey').click()
//         cy.wait(500)
//         cy.get('.delete-button').click()
//         cy.wait(500)
//         cy.get('#closeButton').click()
//         cy.wait(500)
//     })

//     it("Finds all elements in the delete recommendation pop up", () => {
//         cy.get(':nth-child(1) > .primaryKey').click()
//         cy.wait(500)
//         cy.get('.delete-button').should('exist')
//         cy.wait(500)
//         cy.get('.delete-button').click()
//         cy.wait(500)
//         cy.get('.MuiDialog-container > .MuiPaper-root').should('exist')
//         cy.wait(500)
//         cy.get('#closeButton').should('exist')
//         cy.wait(500)
//         cy.get('#WarningRoundedIcon > path').should('exist')
//         cy.wait(500)
//         cy.get('.MuiDialogTitle-root').should('exist')
//         cy.wait(500)
//         cy.get('.MuiDialogContent-root > .MuiTypography-root').should('exist')
//         cy.wait(500)
//         cy.get('#cancelButton').should('exist')
//         cy.wait(500)
//         cy.get('#deleteButton').should('exist')
//         cy.wait(500)
//         cy.get('#closeButton').click()
//         cy.wait(500)
//     })
// });
