import React, { useEffect, useState } from 'react';
import Button from '@material-ui/core/Button';
import { FilterList } from '@material-ui/icons';
import { Grid, TableCell } from '@material-ui/core';
import RecommendationEngineTable from '../../components/RecommendationEngineTable/RecommendationEngineTable';
import { connect } from 'react-redux';
import { mapStateToProps } from '../../redux/SharedReducer/reducer-actions';
import SearchBar from '../../common/SearchBar';

/* istanbul ignore next */
export const RowsToDisplay = (element) => (
    <React.Fragment>
        <TableCell />
        <TableCell component="th" scope="row" padding="default" className="primaryKey" id="tableBody">{element.id}</TableCell>
        <TableCell id="tableBody">{element.netSaving.toFixed(2)}</TableCell>
        <TableCell id="tableBody">{element.returnOnInvestment.toFixed(2)}</TableCell>
        <TableCell id="tableBody">{element.costOfAction.toFixed(2)}</TableCell>
        <TableCell id="tableBody">{element.costOfInaction.toFixed(2)}</TableCell>
        <TableCell id="tableBody">{element.configuredRecommendationId}</TableCell>
    </React.Fragment>
);

export function ResultsPage (props) {

    const { recommendationResultList } = props;
    console.log(recommendationResultList);
    const [resultList, setResultList] = useState(recommendationResultList);
    const [defaultResultList, setDefaultResultList] = useState(recommendationResultList);

    /* istanbul ignore next */
    const headCells = [
        { id: 'id', label: 'Result ID' },
        { id: 'netSaving', label: 'Net Saving' },
        { id: 'returnOnInvestment', label: 'Return on Investment' },
        { id: 'costOfAction', label: 'Cost of Action' },
        { id: 'costOfInaction', label: 'Cost of Inaction' },
        { id: 'configuredRecommendation', label: 'Configured Recommendation' },
    ];

    /* istanbul ignore next */
    const updateSearch = async (input) => {
        const filtered = defaultResultList.filter(result => {
            return result.id.toString().includes(input.toString())
        })
        setResultList(filtered);
    }

    useEffect(() => {
        setResultList(recommendationResultList)
        setDefaultResultList(recommendationResultList)
    }, [recommendationResultList])

    return (
        <div id="main-container">
            <div></div>
            <div>
                <br></br>
                <Grid id="grid-container1" container spacing={1} className="gridContainerStyle">
                    <Grid id="grid1" item>
                        <h3 id="title">Results</h3>
                        <h6 id="subtitle">See the results generated by recommendation jobs</h6>
                    </Grid>
                </Grid>
                <br></br>
            </div>
            <div>
                <div>
                    <Grid id="grid-container2" container spacing={1} className="gridContainerStyle">
                        <Grid item id="data-testid" >
                            <SearchBar
                                placeholder="Search for a recommendation..."
                                onSearchUpdate={updateSearch}
                            />
                        </Grid>
                        <Grid item>
                            <Button size="small" id="filterBtn" endIcon={<FilterList />}>
                                Add Filter
              </Button>
                        </Grid>
                    </Grid>
                </div>
            </div>
            <br></br>
            <RecommendationEngineTable
                rowsValue={RowsToDisplay}
                data={resultList}
                TableTitle={"Recommendation Job Results"}
                onClick={() => { }}
                columnTitles={headCells}
            />
        </div>
    );
}

export default connect(mapStateToProps, null)(ResultsPage);
